import type { Module } from './types';

export const kanjiFoundations: Module = {
  slug: 'kanji-foundations',
  title: 'Kanji Foundations',
  level: 'N5',
  marker: '漢',
  summary:
    'How kanji work, and the roughly hundred characters JLPT N5 expects. Learn the system before the list.',
  lessons: [
    {
      slug: 'how-kanji-work',
      title: 'How kanji work',
      summary: 'Why one character has several readings, and how to stop finding that alarming.',
      minutes: 7,
      body: [
        {
          kind: 'p',
          text: 'Kanji came into Japanese from Chinese over many centuries. Japanese kept the Chinese-derived pronunciations and also attached the characters to words it already had, so most characters carry at least two readings. This is the part that frightens beginners. It is more predictable than it looks.',
        },
        { kind: 'h', text: 'The two reading types' },
        {
          kind: 'table',
          head: ['Type', 'Origin', 'Used when', 'Example with 人'],
          rows: [
            ['音読み (on)', 'Chinese-derived', 'In compound words', '外国人 → がいこくじん'],
            ['訓読み (kun)', 'Native Japanese', 'Standing alone, or with kana', '人 → ひと'],
          ],
        },
        {
          kind: 'note',
          tone: 'tip',
          title: 'A rule of thumb that mostly holds',
          text: 'A kanji alone or followed by hiragana usually takes its kun reading. Two or more kanji stuck together usually take on readings. 山 alone is やま; 富士山 is ふじさん.',
        },
        {
          kind: 'note',
          tone: 'hindi',
          title: 'Tatsam and tadbhav, roughly',
          text: 'Hindi carries Sanskrit-derived words alongside inherited everyday forms of the same root. Japanese does something comparable: the on reading is the borrowed formal layer, the kun reading is the native everyday one. Compounds lean formal; standalone words lean native.',
        },
        { kind: 'h', text: 'Okurigana' },
        {
          kind: 'p',
          text: 'The hiragana trailing a kanji is called okurigana, and it carries the grammar the kanji cannot. 食 holds the meaning "eat"; 食べます, 食べない and 食べた are all the same kanji with different endings.',
        },
        {
          kind: 'note',
          tone: 'warn',
          title: 'Do not learn readings as isolated lists',
          text: 'Memorising that 生 has readings せい, しょう, い, う, は, き, なま in the abstract is close to useless. Learn it inside words like 学生, 先生 and 生まれる, and the readings attach themselves.',
        },
        { kind: 'h', text: 'Stroke order matters more than it seems' },
        {
          kind: 'p',
          text: 'Correct stroke order makes your characters look right, keeps your handwriting legible, and lets you look words up by stroke count. The general rules: top to bottom, left to right, horizontal before the vertical that crosses it, outside before inside.',
        },
      ],
    },
    {
      slug: 'kanji-numbers-time',
      title: 'Kanji: numbers and time',
      summary: 'The first characters to learn, because you already know what they mean.',
      minutes: 6,
      body: [
        {
          kind: 'p',
          text: 'Numbers are the easiest way into kanji. You already know the readings from the numbers module, so only the shape is new.',
        },
        {
          kind: 'vocab',
          title: 'Numbers',
          items: [
            { jp: '一', kana: 'いち / ひと', deva: 'इचि / हितो', en: 'one' },
            { jp: '二', kana: 'に / ふた', deva: 'नि / फुता', en: 'two' },
            { jp: '三', kana: 'さん / みっ', deva: 'सान / मित्', en: 'three' },
            { jp: '四', kana: 'し / よん', deva: 'शि / योन', en: 'four' },
            { jp: '五', kana: 'ご / いつ', deva: 'गो / इत्सु', en: 'five' },
            { jp: '六', kana: 'ろく / むっ', deva: 'रोकु', en: 'six' },
            { jp: '七', kana: 'しち / なな', deva: 'शिचि / नाना', en: 'seven' },
            { jp: '八', kana: 'はち / やっ', deva: 'हाचि', en: 'eight' },
            { jp: '九', kana: 'きゅう / ここの', deva: 'क्यू', en: 'nine' },
            { jp: '十', kana: 'じゅう / とお', deva: 'जू / तोओ', en: 'ten' },
            { jp: '百', kana: 'ひゃく', deva: 'ह्याकु', en: 'hundred' },
            { jp: '千', kana: 'せん', deva: 'सेन', en: 'thousand' },
            { jp: '万', kana: 'まん', deva: 'मान', en: 'ten thousand' },
            { jp: '円', kana: 'えん', deva: 'एन', en: 'yen, circle' },
          ],
        },
        {
          kind: 'vocab',
          title: 'Time and calendar',
          items: [
            { jp: '日', kana: 'にち / ひ', deva: 'निचि / हि', en: 'day, sun' },
            { jp: '月', kana: 'げつ / つき', deva: 'गेत्सु / त्सुकि', en: 'month, moon' },
            { jp: '年', kana: 'ねん / とし', deva: 'नेन / तोशि', en: 'year' },
            { jp: '時', kana: 'じ / とき', deva: 'जि / तोकि', en: 'hour, time' },
            { jp: '分', kana: 'ふん / わ', deva: 'फुन', en: 'minute, to divide' },
            { jp: '半', kana: 'はん', deva: 'हान', en: 'half' },
            { jp: '今', kana: 'いま / こん', deva: 'इमा / कोन', en: 'now' },
            { jp: '前', kana: 'まえ / ぜん', deva: 'माए / ज़ेन', en: 'before, front' },
            { jp: '後', kana: 'あと / ご', deva: 'अतो / गो', en: 'after, behind' },
            { jp: '毎', kana: 'まい', deva: 'माइ', en: 'every' },
            { jp: '週', kana: 'しゅう', deva: 'शू', en: 'week' },
            { jp: '曜', kana: 'よう', deva: 'योउ', en: 'day of the week' },
          ],
        },
        {
          kind: 'note',
          tone: 'tip',
          title: '日 is the character to watch',
          text: 'It appears everywhere and shifts reading constantly: 日本 (にほん), 今日 (きょう), 日曜日 (にちようび), 三日 (みっか). Treat each word as its own item rather than deriving it.',
        },
      ],
    },
    {
      slug: 'kanji-people-nature',
      title: 'Kanji: people, places and nature',
      summary: 'The pictographic characters: the ones that still look like what they mean.',
      minutes: 7,
      body: [
        {
          kind: 'p',
          text: 'Many of the oldest kanji began as pictures, and a few still resemble their subject. Where the picture helps, use it; where it does not, do not force a story.',
        },
        {
          kind: 'vocab',
          title: 'People and family',
          items: [
            { jp: '人', kana: 'ひと / じん / にん', deva: 'हितो / जिन', en: 'person' },
            { jp: '男', kana: 'おとこ / だん', deva: 'ओतोको', en: 'man' },
            { jp: '女', kana: 'おんな / じょ', deva: 'ओन्ना', en: 'woman' },
            { jp: '子', kana: 'こ / し', deva: 'को', en: 'child' },
            { jp: '父', kana: 'ちち / とう', deva: 'चिचि', en: 'father' },
            { jp: '母', kana: 'はは / かあ', deva: 'हाहा', en: 'mother' },
            { jp: '友', kana: 'とも / ゆう', deva: 'तोमो', en: 'friend' },
            { jp: '名', kana: 'な / めい', deva: 'ना / मेइ', en: 'name' },
          ],
        },
        {
          kind: 'vocab',
          title: 'Nature',
          items: [
            { jp: '山', kana: 'やま / さん', deva: 'यामा / सान', en: 'mountain' },
            { jp: '川', kana: 'かわ / せん', deva: 'कावा', en: 'river' },
            { jp: '田', kana: 'た / でん', deva: 'ता', en: 'rice field' },
            { jp: '木', kana: 'き / もく', deva: 'कि / मोकु', en: 'tree, wood' },
            { jp: '花', kana: 'はな / か', deva: 'हाना', en: 'flower' },
            { jp: '水', kana: 'みず / すい', deva: 'मिज़ु / सुइ', en: 'water' },
            { jp: '火', kana: 'ひ / か', deva: 'हि / का', en: 'fire' },
            { jp: '土', kana: 'つち / ど', deva: 'त्सुचि / दो', en: 'earth, soil' },
            { jp: '空', kana: 'そら / くう', deva: 'सोरा / कू', en: 'sky, empty' },
            { jp: '雨', kana: 'あめ / う', deva: 'अमे', en: 'rain' },
          ],
        },
        {
          kind: 'vocab',
          title: 'Places and direction',
          items: [
            { jp: '国', kana: 'くに / こく', deva: 'कुनि / कोकु', en: 'country' },
            { jp: '学', kana: 'がく', deva: 'गाकु', en: 'study, learning' },
            { jp: '校', kana: 'こう', deva: 'कोउ', en: 'school' },
            { jp: '駅', kana: 'えき', deva: 'एकि', en: 'station' },
            { jp: '店', kana: 'みせ / てん', deva: 'मिसे / तेन', en: 'shop' },
            { jp: '上', kana: 'うえ / じょう', deva: 'उए', en: 'above, up' },
            { jp: '下', kana: 'した / か', deva: 'शिता', en: 'below, down' },
            { jp: '中', kana: 'なか / ちゅう', deva: 'नाका / चू', en: 'inside, middle' },
            { jp: '外', kana: 'そと / がい', deva: 'सोतो / गाइ', en: 'outside' },
            { jp: '右', kana: 'みぎ / う', deva: 'मिगि', en: 'right' },
            { jp: '左', kana: 'ひだり / さ', deva: 'हिदारि', en: 'left' },
          ],
        },
        {
          kind: 'note',
          tone: 'tip',
          title: 'Watch for components repeating',
          text: '休 is 人 (person) beside 木 (tree): a person resting against a tree, meaning "rest". Once you know a few basic shapes, complex kanji start decomposing into parts you recognise.',
        },
      ],
    },
    {
      slug: 'kanji-everyday-verbs',
      title: 'Kanji: everyday verbs and adjectives',
      summary: 'The action characters that carry most N5 sentences.',
      minutes: 6,
      body: [
        {
          kind: 'p',
          text: 'These characters appear with okurigana attached, so you will meet them in several forms. Learn the kanji together with its most common conjugation rather than in isolation.',
        },
        {
          kind: 'vocab',
          title: 'Verbs',
          items: [
            { jp: '行', kana: 'い(く) / こう', deva: 'इ(कु)', en: 'go: 行きます' },
            { jp: '来', kana: 'く(る) / らい', deva: 'कु(रु)', en: 'come: 来ます' },
            { jp: '見', kana: 'み(る) / けん', deva: 'मि(रु)', en: 'see: 見ます' },
            { jp: '聞', kana: 'き(く) / ぶん', deva: 'कि(कु)', en: 'listen, ask: 聞きます' },
            { jp: '言', kana: 'い(う) / げん', deva: 'इ(उ)', en: 'say: 言います' },
            { jp: '食', kana: 'た(べる) / しょく', deva: 'ता(बेरु)', en: 'eat: 食べます' },
            { jp: '飲', kana: 'の(む) / いん', deva: 'नो(मु)', en: 'drink: 飲みます' },
            { jp: '読', kana: 'よ(む) / どく', deva: 'यो(मु)', en: 'read: 読みます' },
            { jp: '書', kana: 'か(く) / しょ', deva: 'का(कु)', en: 'write: 書きます' },
            { jp: '話', kana: 'はな(す) / わ', deva: 'हाना(सु)', en: 'speak: 話します' },
            { jp: '買', kana: 'か(う) / ばい', deva: 'का(उ)', en: 'buy: 買います' },
            { jp: '休', kana: 'やす(む) / きゅう', deva: 'यासु(मु)', en: 'rest: 休みます' },
          ],
        },
        {
          kind: 'vocab',
          title: 'Adjectives',
          items: [
            { jp: '大', kana: 'おお(きい) / だい', deva: 'ओओ(कीः)', en: 'big' },
            { jp: '小', kana: 'ちい(さい) / しょう', deva: 'चीः(साइ)', en: 'small' },
            { jp: '高', kana: 'たか(い) / こう', deva: 'ताका(इ)', en: 'tall, expensive' },
            { jp: '安', kana: 'やす(い) / あん', deva: 'यासु(इ)', en: 'cheap' },
            { jp: '新', kana: 'あたら(しい) / しん', deva: 'अतारा(शीः)', en: 'new' },
            { jp: '古', kana: 'ふる(い) / こ', deva: 'फुरु(इ)', en: 'old' },
            { jp: '長', kana: 'なが(い) / ちょう', deva: 'नागा(इ)', en: 'long' },
            { jp: '白', kana: 'しろ(い) / はく', deva: 'शिरो(इ)', en: 'white' },
          ],
        },
        {
          kind: 'note',
          tone: 'tip',
          title: 'Where to go after this',
          text: 'That is roughly the N5 set. Read them everywhere you can: signs, menus, product packaging. Recognition in context builds far faster than flashcards alone, though a small daily review deck helps hold what you have already met.',
        },
      ],
    },
  ],
};
